### ISSUE TITLE
Repo palestra-di-algoritmi

### ISSUE THREAD

**Issue by Stypox** [paradopax/palestradialgoritmi#1]
Ho visto che hai lasciato una stella al mio https://github.com/Stypox/olympiad-exercises, e ho trovato questa repo. Magari ti possono fare utile alcune delle lezioni (in italiano) presenti qui: https://github.com/Stypox/palestra-di-algoritmi ;-)

**Comment by andreadipace** [comment]
Grazie mille! Lo terrò d'occhio per le future lezioni :-)
